### ISSUE TITLE
NoMethodError: undefined method `[]' for #<ActionDispatch::Response::RackBody:0x007f191919fc10>

### ISSUE THREAD

**Issue by HaleTom** [jmuheim/headhunter#17]
Without headhunter, everything is fine:

```
ravi@boxy:~/prj/sample_app(Ch8-basic-login *)$  bundle exec rake test                                                                                                              
Started with run options --seed 30431

  23/23: [====================================================================================================================================] 100% Time: 00:00:01, Time: 00:00:01

Finished in 1.11712s
23 tests, 74 assertions, 0 failures, 0 errors, 0 skips

ravi@boxy:~/prj/sample_app(Ch8-basic-login *)$ 
```

So what is this error?

```
ravi@boxy:~/prj/sample_app(Ch8-basic-login *)$ HEADHUNTER=true bundle exec rake test                                                                                               
Headhunter is removing eventually existing assets... done!
Headhunter is precompiling assets... done!

Started with run options --seed 5390

ERROR["test_valid_login", UsersLoginTest, 1.175529339001514]
 test_valid_login#UsersLoginTest (1.18s)
NoMethodError:         NoMethodError: undefined method `[]' for #<ActionDispatch::Response::RackBody:0x007f191919fc10>
            test/integration/users_login_test.rb:22:in `block in <class:UsersLoginTest>'

ERROR["test_valid_signup", UsersSignupTest, 1.5012131940020481]
 test_valid_signup#UsersSignupTest (1.50s)
NoMethodError:         NoMethodError: undefined method `[]' for #<ActionDispatch::Response::RackBody:0x007f19197691f0>
            test/integration/users_signup_test.rb:21:in `block (2 levels) in <class:UsersSignupTest>'
            test/integration/users_signup_test.rb:20:in `block in <class:UsersSignupTest>'

  23/23: [====================================================================================================================================] 100% Time: 00:00:01, Time: 00:00:01

Finished in 1.56054s
23 tests, 62 assertions, 0 failures, 2 errors, 0 skips

Validated 19 pages.
All pages are valid.

Validated 0 stylesheets.
All stylesheets are valid.

Found 0 CSS selectors.
All selectors are in use.

Headhunter is removing precompiled assets... done!
ravi@boxy:~/prj/sample_app(Ch8-basic-login *)[1]$ 
```

**Comment by jmuheim** [comment]
Sadly this project isn't maintained anymore.
